### ISSUE TITLE
Error after upgrading to 1.6.3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by junpataleta** [FMCorz/mdk#161]
On Ubuntu 16.04, I upgraded MDK to 1.6.3. After the upgrade, I got the following error:
> AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

The workaround is to reinstall pyopenssl. (Upgrading could have probably worked too.)

**Comment by FMCorz** [comment]
Closing this, as it seems to fix itself when re-installing the requirements. Thanks.
